# Generated by Django 4.2.16 on 2026-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(blank=True, default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_stock',
            field=models.PositiveIntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_stock',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, default='kg', max_length=10),
        ),
    ]
