# Generated by Django 4.2.16 on 2026-07-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=50)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('mse', models.FloatField(blank=True, help_text='Mean Squared Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('mape', models.FloatField(blank=True, help_text='Mean Absolute Percentage Error', null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_file', models.CharField(blank=True, max_length=500)),
                ('training_data_points', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_models', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='StockForecastSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('snapshot_date', models.DateField()),
                ('projected_stock', models.DecimalField(decimal_places=3, max_digits=15)),
                ('projected_demand', models.DecimalField(decimal_places=3, max_digits=15)),
                ('projected_reorder', models.BooleanField(default=False)),
                ('stockout_risk', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='none', max_length=20)),
                ('suggested_order_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['snapshot_date'],
                'unique_together': {('product', 'warehouse', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('forecast_date', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('predicted_demand', models.DecimalField(decimal_places=3, max_digits=15)),
                ('predicted_demand_lower', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('predicted_demand_upper', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('actual_demand', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('forecast_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_used', models.CharField(default='prophet', max_length=50)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=95, max_digits=5)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'unique_together': {('product', 'warehouse', 'forecast_date', 'period_type')},
            },
        ),
    ]
